# Generated by Django 3.0.4 on 2020-04-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
