# Generated by Django 3.0.4 on 2020-04-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0002_remove_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='yearReleased',
        ),
    ]
