# Generated by Django 3.0.4 on 2020-04-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0003_remove_movie_yearreleased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='belongsToCollection',
        ),
    ]
