# Generated by Django 3.0.4 on 2020-04-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0006_auto_20200419_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfilePictures',
            fields=[
                ('groupPicID', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(default=None, max_length=2048)),
                ('S3Key', models.CharField(default=None, max_length=2048)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogTemp.UserGroup')),
            ],
        ),
    ]
