# Generated by Django 3.0.4 on 2020-04-19 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0007_groupprofilepictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofilepictures',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
