# Generated by Django 3.0.4 on 2020-04-20 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0008_groupprofilepictures_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePictures',
            fields=[
                ('userProPicID', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(default=None, max_length=2048)),
                ('S3Key', models.CharField(default=None, max_length=2048)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
