# Generated by Django 3.0.4 on 2020-04-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0010_movie_posters3key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('tvID', models.AutoField(primary_key=True, serialize=False)),
                ('backDropPath', models.TextField(max_length=2048)),
                ('episodeRunTime', models.IntegerField(blank=True, default=None)),
                ('firstAirDate', models.DateField(blank=True, default=None)),
                ('genres', models.TextField(default='', max_length=2048)),
                ('tmdbID', models.IntegerField(blank=True, default=None)),
                ('inProduciton', models.BooleanField(default=False)),
                ('lastAirDate', models.DateField(blank=True, default=None)),
                ('lastEpisodeToAir', models.TextField(blank=True, default=None, max_length=4096)),
                ('showTitle', models.TextField(blank=True, default=None, max_length=4086)),
                ('nextEpisodeToAir', models.TextField(blank=True, default=None, max_length=4086)),
                ('networks', models.TextField(blank=True, default=None, max_length=4086)),
                ('numberEpisodes', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, default='', max_length=8192)),
                ('popularity', models.DecimalField(blank=True, db_index=True, decimal_places=10, default=0.0, max_digits=12)),
                ('posterPath', models.TextField(blank=True, default='', max_length=2048)),
                ('seasons', models.TextField(blank=True, default='', max_length=8192)),
                ('status', models.TextField(blank=True, default='', max_length=256)),
                ('showType', models.TextField(blank=True, default='', max_length=256)),
            ],
        ),
    ]
