# Generated by Django 3.0.4 on 2020-04-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0013_tvshow_numberseasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='inProduciton',
            new_name='inProduction',
        ),
    ]
