# Generated by Django 3.0.4 on 2020-04-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0014_auto_20200425_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='tvShowID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TV', to='catalogTemp.TVShow'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='movieID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='catalogTemp.Movie'),
        ),
    ]
