# Generated by Django 3.0.4 on 2020-05-01 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0017_auto_20200430_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='posterS3Key',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='CastOfMovies',
            fields=[
                ('castMovieID', models.AutoField(primary_key=True, serialize=False)),
                ('tmdbMovieID', models.IntegerField(default=None)),
                ('tmdbCastID', models.IntegerField(default=None)),
                ('characterName', models.CharField(blank=True, default=None, max_length=2098)),
                ('creditID', models.TextField(blank=True, default=None, max_length=2098)),
                ('gender', models.IntegerField(blank=True, default=None)),
                ('tmdbID2', models.IntegerField(blank=True, default=None)),
                ('actorName', models.CharField(blank=True, default=None, max_length=2098)),
                ('order', models.IntegerField(blank=True, default=None)),
                ('profile_path', models.CharField(blank=True, default=None, max_length=2048)),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogTemp.Movie')),
            ],
        ),
    ]
