# Generated by Django 3.0.4 on 2020-05-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0019_auto_20200503_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='tmdbID',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
