# Generated by Django 3.0.4 on 2020-05-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0022_auto_20200503_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castofmovies',
            name='movieID',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
