# Generated by Django 3.0.4 on 2020-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0023_auto_20200503_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castofmovies',
            name='tmdbID2',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
