# Generated by Django 3.0.4 on 2020-05-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0025_auto_20200504_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='castofmovies',
            unique_together={('tmdbMovieID', 'tmdbCastID')},
        ),
    ]
