# Generated by Django 3.0.4 on 2020-05-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0026_auto_20200504_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='castofmovies',
            unique_together=set(),
        ),
    ]
