# Generated by Django 3.0.4 on 2020-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0027_auto_20200504_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castofmovies',
            name='tmdbMovieID',
            field=models.IntegerField(db_index=True, default=None),
        ),
    ]
