# Generated by Django 3.0.4 on 2020-05-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0028_auto_20200505_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierecommendation',
            old_name='reccomenderRating',
            new_name='recommenderRating',
        ),
    ]
