# Generated by Django 3.0.4 on 2020-05-09 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0029_auto_20200508_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='commentID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiverUserID', to='catalogTemp.CommentOnGroupMovieRecommendation'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='groupRecID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogTemp.MovieRecommendationWithinGroup'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='receiverUserID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiverUserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
