# Generated by Django 3.0.4 on 2020-05-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0030_auto_20200509_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='commentID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverUserID', to='catalogTemp.CommentOnGroupMovieRecommendation'),
        ),
    ]
