# Generated by Django 3.0.4 on 2020-05-10 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0031_auto_20200509_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecommendationwithingroup',
            name='memberID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
