# Generated by Django 3.0.4 on 2020-05-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0032_auto_20200510_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
