# Generated by Django 3.0.4 on 2020-05-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0033_usernotifications_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRankings',
            fields=[
                ('rankingsID', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfRankings', models.TextField(max_length=512)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('rankingsS3Key', models.TextField(blank=True, max_length=512, null=True)),
                ('creatorUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankingsItems',
            fields=[
                ('rankingItemID', models.AutoField(primary_key=True, serialize=False)),
                ('rankingInList', models.IntegerField(default=None)),
                ('rankingsDescription', models.TextField(blank=True, default=None, max_length=2024, null=True)),
                ('movieID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movieitem', to='catalogTemp.Movie')),
                ('rankingList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='catalogTemp.UserRankings')),
                ('tvShowID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TVitem', to='catalogTemp.TVShow')),
            ],
        ),
    ]
