# Generated by Django 3.0.4 on 2020-06-14 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0036_userrankings_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingsitems',
            name='rankingInList',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingsitems',
            name='rankingList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='catalogTemp.UserRankings'),
        ),
    ]
