# Generated by Django 3.0.4 on 2020-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0037_auto_20200614_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrankings',
            name='publicToGroups',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='rankingsitems',
            unique_together={('tvShowID', 'rankingList'), ('movieID', 'rankingList')},
        ),
    ]
