# Generated by Django 3.0.4 on 2020-06-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0038_auto_20200614_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.IntegerField(blank=True, unique=True)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
