# Generated by Django 3.0.4 on 2020-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0039_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phoneNumber',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
