# Generated by Django 3.0.4 on 2020-06-20 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0040_auto_20200619_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallFeedExclusions',
            fields=[
                ('exclusionID', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogTemp.UserGroup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userID', 'groupID')},
            },
        ),
    ]
