# Generated by Django 3.0.4 on 2020-06-20 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0041_overallfeedexclusions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('reportComment', models.CharField(blank=True, max_length=4096, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('commentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogTemp.CommentOnGroupMovieRecommendation')),
                ('groupRecID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogTemp.MovieRecommendationWithinGroup')),
                ('reporterUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
