# Generated by Django 3.0.4 on 2020-06-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0042_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('googleBookID', models.IntegerField(unique=True)),
                ('bookTitle', models.CharField(default=None, max_length=4096)),
                ('authors', models.CharField(default='', max_length=8192)),
                ('publisher', models.TextField(default='', max_length=8192)),
                ('description', models.TextField(default='', max_length=16384)),
                ('pageCount', models.IntegerField(blank=True, default=None, null=True)),
                ('categories', models.TextField(blank=True, default='', max_length=4096, null=True)),
                ('thumbnail', models.TextField(blank=True, default='', max_length=4096, null=True)),
                ('language', models.TextField(blank=True, default='', max_length=128, null=True)),
                ('infoLink', models.TextField(blank=True, default='', max_length=4096, null=True)),
                ('previewLink', models.TextField(blank=True, default='', max_length=4096, null=True)),
                ('canonicalVolumeLink', models.TextField(blank=True, default='', max_length=4096, null=True)),
            ],
        ),
    ]
