# Generated by Django 3.0.4 on 2020-06-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0044_movierecommendation_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='googleBookID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
