# Generated by Django 3.0.4 on 2020-07-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0045_auto_20200625_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('podcastID', models.AutoField(primary_key=True, serialize=False)),
                ('spotifyPodcastID', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(default='', max_length=8192)),
                ('spotifyURL', models.TextField(blank=True, default='', max_length=4096, null=True)),
                ('spotifyImageURL', models.TextField(blank=True, default='', max_length=512)),
                ('adult', models.TextField(default='False', max_length=128)),
                ('title', models.TextField(default=None, max_length=8192)),
                ('publisher', models.TextField(blank=True, default='', max_length=8192)),
            ],
        ),
        migrations.AddField(
            model_name='rankingsitems',
            name='bookID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='catalogTemp.Book'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='bookID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book2', to='catalogTemp.Book'),
        ),
    ]
