# Generated by Django 3.0.4 on 2020-07-11 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0048_auto_20200706_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('episodeID', models.AutoField(primary_key=True, serialize=False)),
                ('audioPreviewURL', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=16120, null=True)),
                ('duration_ms', models.TextField(blank=True, default='0', max_length=255, null=True)),
                ('explicit', models.BooleanField(default='False')),
                ('spotifyURL', models.TextField(blank=True, default=None, max_length=512, null=True)),
                ('spotifyID', models.CharField(max_length=255, unique=True)),
                ('spotifyImageURL', models.TextField(blank=True, default='', max_length=512)),
                ('name', models.TextField(blank=True, default='', max_length=4012)),
                ('release_date', models.TextField(blank=True, default='NA', max_length=127)),
            ],
        ),
    ]
