# Generated by Django 3.0.6 on 2020-07-31 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0050_podcastepisode_podcastid'),
    ]

    operations = [
    ]
