# Generated by Django 2.2 on 2021-02-16 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogTemp', '0053_auto_20210105_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='groupJoinCode',
            field=models.CharField(db_index=True, default=None, max_length=128, unique=False),
        ),
        migrations.CreateModel(
            name='SignUpCode',
            fields=[
                ('codeID', models.AutoField(primary_key=True, serialize=False)),
                ('signUpCode', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='endorsementsonmovierecsingroups',
            name='recID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='catalogTemp.MovieRecommendation'),
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='episodeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='episode', to='catalogTemp.PodcastEpisode'),
        ),
        migrations.AddField(
            model_name='rankingsitems',
            name='episodeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ep', to='catalogTemp.PodcastEpisode'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='groupJoinCode',
            field=models.CharField(db_index=True, default=None, max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='endorsementsonmovierecsingroups',
            unique_together={('endorserUserID', 'recID')},
        ),
        migrations.AlterUniqueTogether(
            name='rankingsitems',
            unique_together={('episodeID', 'rankingList'), ('tvShowID', 'rankingList'), ('movieID', 'rankingList'),
                             ('bookID', 'rankingList')},
        ),
        migrations.CreateModel(
            name='SignUpCodeGroups',
            fields=[
                ('signUpGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('codeID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                             to='catalogTemp.SignUpCode')),
                ('groupID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                              to='catalogTemp.UserGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='endorsementsonmovierecsingroups',
            name='postID',
        ),
    ]
