# Generated by Django 2.2 on 2021-02-21 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0055_auto_20210221_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
