# Generated by Django 2.2 on 2021-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0056_auto_20210221_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='backdropPath',
            field=models.TextField(blank=True, default=None, max_length=2048),
        ),
    ]
