# Generated by Django 2.2 on 2021-02-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0057_auto_20210221_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='episodeRunTime',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='homepage_link',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='numberEpisodes',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='numberSeasons',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='status',
        ),
        migrations.AddField(
            model_name='commentongroupmovierecommendation',
            name='commentParentID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='backdropPath',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='firstAirDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='lastAirDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='posterPath',
            field=models.TextField(blank=True, default='', max_length=2048, null=True),
        ),migrations.RemoveField(
            model_name='tvshow',
            name='lastEpisodeToAir',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='networks',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='nextEpisodeToAir',
        ),
    ]
