# Generated by Django 2.2 on 2021-03-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogTemp', '0058_auto_20210221_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentongroupmovierecommendation',
            name='commentDepth',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
